### ISSUE TITLE
about link px4

### ISSUE THREAD

**Issue by Miss-yins** [risckaust/risc-documentations#4]
hello, thanks for your share. Now i am following your article which indoor flying, but i can not link the px4 by telem2, can i insteand i by usb link? Could you tell me how to do that? Thanks.

**Comment by ghost** [comment]
Hello,

What is the hardware you are using? In the case of MindPX, you can directly use micro usb cable. If you are using Pixhawk, then you have to use USB TTL serial connector. Use only TX, RX, and GND and connect them to TELEM2 port.
